### ISSUE TITLE
Support for User model

### ISSUE THREAD

**Issue by deiucanta** [deiucanta/laravel-smart#15]
The default `User` model extends `Illuminate\Foundation\Auth\User`. Since it's not possible to extend two classes, how can we solve this?

**Comment by deiucanta** [comment]
```php
<?php

trait SmartModel { ... }

class Model extends Illuminate\Database\Eloquent\Model {
    use SmartModel;
    public function __construct() { ... }
}

class Authenticable extends Illuminate\Foundation\Auth\User {
    use SmartModel;
    public function __construct() { ... }
}
```

**Comment by robsontenorio** [comment]
Hm... it seems weird

**Comment by deiucanta** [comment]
It would be weird to expose this to the developer. But what about having this beside the scenes?

The user would extends either `Deiucanta\Smart\Model` or `Deiucanta\Smart\Authenticable`.
