### ISSUE TITLE
rule customization

### ISSUE THREAD

**Issue by vladflip** [deiucanta/laravel-smart#2]
What about a field customization per request? There are cases when you need to validate the fields differently (basic example is admin user). This is done with form requests. So I’m guessing this package should expose a static method in a model which returns new customized rules (including complete rule removal) which you can use in a form request.

**Comment by robsontenorio** [comment]
I think roles are out from escope this package.

**Comment by deiucanta** [comment]
You're right @robsontenorio. User roles are out of the scope of this package but validation rules are right at the core. The questions is this: can user **roles** change validation **rules**?

**Comment by deiucanta** [comment]
I will close this until someone provides a real scenario where this is required.
