### ISSUE TITLE
Cache `$model->fields()`

### ISSUE THREAD

**Issue by deiucanta** [deiucanta/laravel-smart#21]
- this would improve performance
- we can cache it as a collection
- caching should be inside a static property and based on the class name

**Comment by robsontenorio** [comment]
I m not sure if it’s necessary. On real world app it wont be touched most of time. 

Just used to make tests.

**Comment by deiucanta** [comment]
Currently `$model->fields()` is called whenever a new model is created. When `$model->fields()` is called, the `Field` instances are created again and again. That's why I think we should "cache" them.

```php
public static function getFields()
{
    $model = get_class(static);
    
    if (!isset(static::$fieldsCache[$model])) {
        $instance = new static;
        static::$fieldsCache[$model] = $instance->fields();
    }

    static::$fieldsCache[$model]
}
```

The code is not tested but you should be able to get the idea.
