### ISSUE TITLE
Support virtual fields for mysql

### ISSUE THREAD

**Issue by terranc** [deiucanta/laravel-smart#26]
Those are available since MySQL 5.7.

**Comment by deiucanta** [comment]
@terranc can you please provide us a real-world scenario where you would use virtual fields?

**Comment by terranc** [comment]
the migration after:
```php

    public function up()
    {
        Schema::create('awards', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('name', 100)->nullable()->default(null);
            $table->decimal('price', 10, 2)->default('0');
            $table->decimal('service_fee', 10, 2)->default('0');
            $table->decimal('sale_price', 10, 2)->virtualAs('`price` + `service_fee`');
            $table->softDeletes();
            $table->timestamps();
        });
    }
```

**Comment by deiucanta** [comment]
@terranc Thank you! Makes sense.

You could do this using a simple Eloquent accessor/getter. This seems to be a read-only field.

At the moment, we will not support this feature for the following reasons

- the same thing can be implemented using existing functionality
- it's not supported by all databases
